name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ 13.53.138.77 }}
        USERNAME: ${{ ubuntu }}
        PORT: ${{ 22 }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/home/ubuntu/"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ 13.53.138.77 }}
        USERNAME: ${{ ubuntu }}
        PORT: ${{ 22 }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
